# Generated by Django 3.2.9 on 2021-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagenes_blog/publicaciones/'),
        ),
    ]
